stages:
  - build
  - quality
  - test
  - security
  - docs
  - publish

include:
  - project: "jatic/kitware/devel"
    ref: main
    file: ".gitlab-ci.yml"

  # job overrides specific to this repo
  - local: .gitlab-ci/.gitlab-build.yml
  - local: .gitlab-ci/.gitlab-test.yml
  - local: .gitlab-ci/.gitlab-security.yml