repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
      types: [file, python]
-   repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        types: [file, python]
        language: system
      - id: ruff
        name: ruff
        entry: poetry run ruff --fix
        types: [file, python]
        language: system
      - id: mypy
        name: mypy
        entry: poetry run mypy
        types: [file, python]
        language: system
