###############################################################################
# Stage -- Documentation
###############################################################################

.docs-setup:
  extends: .shared-setup
  stage: docs
  needs: [build:cache]
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only dev-docs,dev-testing
    - !reference [.needs-headless-opencv, before_script]

pages-branch:
  extends: .docs-setup
  artifacts:
      expose_as: 'Documentation Build'
      paths:
        - docs/_build/html/
  environment:
      name: docs-preview/$CI_MERGE_REQUEST_IID
      url: "https://jatic.pages.jatic.net/-/kitware/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/docs/_build/html/index.html"
      auto_stop_in: 1 week
  script:
    - cd docs
    - poetry run make html
  variables:
      PUBLIC_URL: "/-/kitware/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/docs/_build/html/"
  rules:
    # Don't run this rule if on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - !reference [.docs-setup, rules]

pages-main:
  extends: .docs-setup
  script:
    - cd docs
    - poetry run make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  rules:
    # Only run this rule if on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never  # explicit fail-exclude terminal condition.