###############################################################################
# Stage -- Build
###############################################################################
# 
# Overrides:
# 
# 1) Installed "tools" extras
#
###############################################################################

build:cache:
  script:
    - poetry install --sync --only main,linting,tests,docs --extras tools