###############################################################################
# Stage -- Unit Testing
###############################################################################
#
# Overrides:
#
# 1) Installed "tools" extras
# 2) nrtk-jatic specific notebooks.
#
###############################################################################

notebooks:
  rules: !reference [.notebooks, rules]
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "docs/examples"
        NOTEBOOK_FILE: [
          "jatic-image-classifier-protocol.ipynb",
          "jatic-object-detector-protocol.ipynb",
          "jatic-perturbations.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/armory"
        NOTEBOOK_FILE: [
          "xaitk-armory.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/gradio"
        NOTEBOOK_FILE: [
          "model-comparison.ipynb",
          "xaitk-gradio.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/huggingface"
        NOTEBOOK_FILE: [
          "xaitk-accelerate.ipynb",
          "xaitk-huggingface.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/lightning"
        NOTEBOOK_FILE: [
          "xaitk-lightning.ipynb",
        ]
      - NOTEBOOK_DIR: "docs/examples/mlflow"
        NOTEBOOK_FILE: [
          "MNIST_MLFlow_scikit_saliency.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/shared_interest"
        NOTEBOOK_FILE: [
          "xaitk-shared_interest.ipynb"
        ]

pytest-extras:
  allow_failure: false
  variables:
    EXTRAS: "tools docker"

# This is a temporary override while we wait for devel-jatic to support 3.13
.python-versions:
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.10", "3.11", "3.12", "3.13" ]
