###############################################################################
# Stage -- Unit Testing
###############################################################################
#
# Overrides:
#
# 1) Installed "tools" extras
# 2) nrtk-jatic specific notebooks.
#
###############################################################################

.test-setup:
  before_script:
    - !reference [.shared-setup, before_script]
    - poetry install --sync --only main,tests --extras tools

notebooks:
  parallel:
    matrix:
      # Sequences combinatorically combine within a list entry
      - NOTEBOOK_DIR: "docs/examples"
        NOTEBOOK_FILE: [
          "jatic-image-classifier-protocol.ipynb",
          "jatic-object-detector-protocol.ipynb",
          jatic-perturbations.ipynb
        ]
      - NOTEBOOK_DIR: "docs/examples/armory"
        NOTEBOOK_FILE: [
          "xaitk-armory.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/gradio"
        NOTEBOOK_FILE: [
          "model-comparison.ipynb",
          "xaitk-gradio.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/huggingface"
        NOTEBOOK_FILE: [
          "xaitk-accelerate.ipynb",
          "xaitk-huggingface.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/lightning"
        NOTEBOOK_FILE: [
          "xaitk-lightning.ipynb",
        ]
      - NOTEBOOK_DIR: "docs/examples/mlflow"
        NOTEBOOK_FILE: [
          "MNIST_MLFlow_scikit_saliency.ipynb"
        ]
      - NOTEBOOK_DIR: "docs/examples/shared_interest"
        NOTEBOOK_FILE: [
          "xaitk-shared_interest.ipynb"
        ]
