###############################################################################
# Stage -- Build and publishd Docker images
###############################################################################
include:
  # the base container pipeline
  - project: "jatic/kitware/devel-jatic"
    ref: "main"
    file: ".gitlab-ci/pipelines/.gitlab-container.yml"

test:
  script:
    - apk add --no-cache curl
    - curl -sfL  https://farm1.staticflickr.com/74/202734059_fcce636dcd_z.jpg -o tests/data/example_img.jpeg

    # Cannot mount a volumne in GitLab CI/CD, so we have
    # to manually copy the files into the image before testing
    - echo "FROM $IMAGE_PATH" > Dockerfile.temp
    - echo "COPY tests/data /root/input" >> Dockerfile.temp
    - echo "COPY . /root/output" >> Dockerfile.temp
    - docker build -f Dockerfile.temp -t ${CONTAINER_NAME}:temp .
    - docker run --rm ${CONTAINER_NAME}:temp

    # Clean up the temporary docker image
    - docker rmi ${CONTAINER_NAME}:temp || true
